image: docker:19.03.12

before_script:
  - docker info

services:
  - docker:19.03.12-dind

build:
  stage: build
  script:
    - docker build --force-rm --no-cache -t example-rails-ci -f dockerfiles/ci.Dockerfile .
    - docker run example-rails-ci bundler-audit
