image: registry.rscz.ru:5005/arteme/example-rails-ci

variables:
  TIMEZONE: "Europe/Moscow"

cache:
  #untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/
    - vendor/ruby/
    - .bundled/
    - .yarn


build:
  stage: build
  script:
    - ls
    - printenv
    - ruby -v
    - gem env
    - bundle env
    - bundle config set path 'vendor/ruby'
    - bundle install --jobs $(nproc)
    - bundler-audit
    - brakeman
